# Required execution order:
# 1. Run data_grid.py to preprocess the data and generate posterior summaries.
# 2. Run grf.py to interpolate missing spatial estimates and create figures.

"""
Interpolate and visualise spatial posterior estimates of temperature acceleration.

This script:
1. loads posterior summaries generated by data_grid.py;
2. identifies grid cells with missing posterior estimates;
3. interpolates missing spatial values using a Gaussian random field;
4. generates maps of posterior acceleration and exceedance probability;
5. determines when probability thresholds are first exceeded;
6. summarises threshold exceedance over land and ocean.

Run data_grid.py before running this script.
"""
from pathlib import Path
import json

import numpy as np
import matplotlib.pyplot as plt
import matplotlib.gridspec as gridspec
import matplotlib.patches as mpatches
import matplotlib.colors as mcolors
import netCDF4 as nc
import cartopy.crs as ccrs
import cartopy.feature as cfeature

from scipy.special import gamma, kv
from scipy.optimize import minimize
from scipy.ndimage import zoom
from matplotlib.ticker import FuncFormatter, MaxNLocator
from global_land_mask import globe


# Repository paths
PROJECT_ROOT = Path(__file__).resolve().parent
DATA_DIR = PROJECT_ROOT / "data"
RESULTS_DIR = PROJECT_ROOT / "results"

# Create the results directory if it does not exist
RESULTS_DIR.mkdir(parents=True, exist_ok=True)

# Map projection used for spatial figures
projection = ccrs.Robinson()

def custom_latitude_formatter(lat, pos):
    direction = "N" if lat >= 0 else "S"
    return f"{abs(int(lat))}°{direction}"


def custom_longitude_formatter(lon, pos):
    direction = "E" if lon >= 0 else "W"
    return f"{abs(int(lon))}°{direction}"

def grf(a):
    """
    Interpolate missing grid-cell values using a Gaussian random field.

    A Matérn covariance model is fitted to the observed grid cells. Conditional
    expectations under the fitted model are then used to fill missing cells.

    Parameters
    ----------
    values : numpy.ndarray
        Two-dimensional spatial field containing observed values and NaNs.

    Returns
    -------
    numpy.ndarray
        Spatial field with missing values replaced by conditional GRF means.

    Notes
    -----
    Spatial locations are represented by grid indices rather than physical
    distances in latitude and longitude.
    """
    def pos(n, m):
        i,j = np.indices((n,m))
        return np.stack((i,j),axis=-1)
    x_known = a.flatten()
    s_known = pos(a.shape[0],a.shape[1]).reshape(-1, 2)
    keep = ~np.isnan(x_known)
    x_known = x_known[keep];s_known = s_known[keep]
    s_unknown = pos(a.shape[0],a.shape[1]).reshape(-1, 2)
    s_unknown = s_unknown[~keep]
    
    def gen_cov_mat(s,sig,nu,l):
        n = s.shape[0]
        cov_matrix = np.zeros((n,n))
        h = s[:, np.newaxis, :] - s[np.newaxis, :, :]
        h = np.linalg.norm(h,axis=-1)
        np.fill_diagonal(h,10)
        cov_matrix = sig**2*(2**(1-nu)/gamma(nu))*((h/l)**nu)*kv(nu,h/l)
        np.fill_diagonal(cov_matrix,sig**2)
        return cov_matrix
    
    def mean(s,mu):
        n = s.shape[0]
        return mu*np.ones(n)
    
    def log_like_simp(params,sig,x,s):
        nu,l = params
        cov_mat = gen_cov_mat(s,sig,nu,l)
        L = np.linalg.cholesky(cov_mat)
        n = x.shape[0]
        L_inv = np.linalg.solve(L,np.eye(n))
        cov_inv = L_inv.T@L_inv
        log_det_cov = 2*np.sum(np.log(np.diag(L)))
        mu = np.sum(cov_inv@x)/np.sum(cov_inv)*np.ones(n)
        return n*np.log((x-mu).T@cov_inv@(x-mu))+log_det_cov
    
    def callback(xk):
        print("Evaluating at:", xk)
    nu,l = minimize(log_like_simp,[1,1],method='SLSQP',args=(1,x_known,s_known),bounds=[(1e-6,2),(1e-6,50)],callback=callback).x
    mu = np.sum(gen_cov_mat(s_known,1,nu,l)@x_known)/np.sum(gen_cov_mat(s_known,1,nu,l))
    sig = 1/len(x_known)*x_known.T@np.linalg.solve(gen_cov_mat(s_known,1,nu,l),np.eye(s_known.shape[0]))@x_known
    
    def pred(x_known,s_known,s_unknown,mu,sig,nu,l):
        s = np.concatenate((s_unknown,s_known))
        n = s_known.shape[0]
        d = s_unknown.shape[0]
        full_cov = gen_cov_mat(s,sig,nu,l)
        cov_un = full_cov[:d,:d]
        cov_kn = full_cov[d:,d:]
        cov_un_kn = full_cov[:d,d:]
        cov_kn_inv = np.linalg.solve(cov_kn,np.eye(n))
        E_un = mean(s_unknown,mu)+cov_un_kn@cov_kn_inv@(x_known-mean(s_known,mu))
        cond_cov = cov_un - cov_un_kn@cov_kn_inv@cov_un_kn.T
        return E_un,np.diag(cond_cov)
    
    x_unknown,cov_unknown = pred(x_known,s_known,s_unknown,mu,sig,nu,l)
    x = np.zeros(len(x_unknown)+len(x_known));x[keep] = x_known;x[~keep] = x_unknown
    return x.reshape(a.shape)

# %% Helper function for loading dataset coordinates
def load_coordinates(data_origin):
    """
    Load the latitude and longitude coordinates for a climate dataset.

    Parameters
    ----------
    data_origin : str
        Dataset identifier. Supported values are "hadcrut", "noaa",
        "berkeley", and "era5".

    Returns
    -------
    tuple of numpy.ndarray
        Latitude and longitude coordinates.
    """
    data_path = DATA_DIR / f"data_grid_{data_origin}.nc"

    if not data_path.exists():
        raise FileNotFoundError(
            f"Input dataset was not found: {data_path}"
        )

    with nc.Dataset(str(data_path), mode="r") as fname:
        if data_origin == "hadcrut":
            lat = fname.variables["latitude"][:].data
            lon = fname.variables["longitude"][:].data

        elif data_origin == "noaa":
            lat = fname.variables["lat"][:].data
            lon = fname.variables["lon"][:].data - 180

        elif data_origin == "berkeley":
            lat = (
                fname.variables["latitude"][:]
                .data.reshape(180 // 5, 5)
                .mean(axis=1)
            )
            lon = (
                fname.variables["longitude"][:]
                .data.reshape(360 // 5, 5)
                .mean(axis=1)
            )

        elif data_origin == "era5":
            raw_lat = fname.variables["latitude"][:].data
            raw_lon = fname.variables["longitude"][:].data

            # Downscale the original ERA5 grid to 36 latitude bands.
            lat = np.flipud(
                np.mean(
                    [
                        raw_lat[i * 21 - i : (i + 1) * 21 - i]
                        for i in range(36)
                    ],
                    axis=1,
                )
            )

            # Downscale the original ERA5 grid to 72 longitude bands.
            lon = (
                np.mean(
                    [
                        raw_lon[1:][i * 19 + i : (i + 1) * 19 + i]
                        for i in range(72)
                    ],
                    axis=1,
                )
                - 180
            )

        else:
            raise ValueError(
                "data_origin must be 'hadcrut', 'noaa', "
                "'berkeley', or 'era5'."
            )

    return np.asarray(lat), np.asarray(lon)


# %% Analysis configuration

# Dataset used for interpolation and inspection.
data_origin = "era5"

# Quantity extracted from the posterior result files:
# "prob_g_0" contains posterior sign probabilities.
# "post_means" contains posterior parameter means.
dataset = "prob_g_0"

start_year = 1970

# The end year is exclusive. For example, 2026 contains observations
# through the end of 2025.
end_years = [
    1990,
    1995,
    2000,
    2005,
    2010,
    2015,
    2020,
    2026,
]

if dataset not in {"prob_g_0", "post_means"}:
    raise ValueError(
        "dataset must be either 'prob_g_0' or 'post_means'."
    )

lat, lon = load_coordinates(data_origin)

result_dir = RESULTS_DIR / data_origin
result_dir.mkdir(parents=True, exist_ok=True)


# %% Load posterior acceleration estimates

coeff = np.full(
    (len(end_years), len(lat), len(lon)),
    np.nan,
    dtype=float,
)

for period_index, end_year in enumerate(end_years):
    input_path = result_dir / (
        f"{dataset}_{data_origin}_{start_year}_{end_year}.txt"
    )

    if not input_path.exists():
        raise FileNotFoundError(
            f"Posterior result file was not found: {input_path}"
        )

    with input_path.open("r", encoding="utf-8") as file:
        posts = json.load(file)

    for lat_index, latitude in enumerate(lat):
        for lon_index, longitude in enumerate(lon):
            coordinate = f"{latitude} {longitude}"
            posterior_values = posts.get(coordinate)

            if (
                posterior_values is not None
                and len(posterior_values) > 2
                and posterior_values[2] is not None
            ):
                # The third posterior entry is the quadratic coefficient a_2,
                # interpreted as the local acceleration parameter.
                coeff[
                    period_index,
                    lat_index,
                    lon_index,
                ] = posterior_values[2]


# Use a consistent spatial support across all truncation periods.
# A grid cell is treated as missing in every period if it is unavailable
# in at least one period.
available_in_all_periods = np.all(np.isfinite(coeff), axis=0)
coeff[:, ~available_in_all_periods] = np.nan

for end_year, field in zip(end_years, coeff):
    missing_count = np.isnan(field).sum()

    print(
        f"{data_origin.upper()} {start_year}-{end_year}: "
        f"{missing_count} grid cells require interpolation"
    )


# %% Plot posterior fields before GRF interpolation

for period_index, end_year in enumerate(end_years):
    field = coeff[period_index]
    field_zoom = zoom(field, (4, 4), order=1)

    fig, ax = plt.subplots(
        figsize=(10, 5),
        subplot_kw={"projection": projection},
    )

    if dataset == "prob_g_0":
        vmax = 1
    else:
        vmax = np.nanmax(coeff)

    image = ax.imshow(
        np.flipud(field_zoom),
        cmap="viridis",
        transform=ccrs.PlateCarree(),
        vmax=vmax,
    )

    ax.coastlines(color="black", linewidth=0.5)
    ax.add_feature(
        cfeature.BORDERS,
        edgecolor="black",
        linewidth=0.5,
    )

    gridlines = ax.gridlines(
        draw_labels=True,
        linestyle="--",
        linewidth=0.5,
        color="gray",
    )
    gridlines.top_labels = False
    gridlines.right_labels = False
    gridlines.xformatter = FuncFormatter(
        custom_longitude_formatter
    )
    gridlines.yformatter = FuncFormatter(
        custom_latitude_formatter
    )
    gridlines.ylocator = MaxNLocator(nbins=9)

    fig.colorbar(image, ax=ax, shrink=0.8)

    if dataset == "post_means":
        ax.set_title(
            f"Acceleration coefficient: "
            f"{start_year}-{end_year}"
        )
    else:
        ax.set_title(
            f"Probability of positive acceleration: "
            f"{start_year}-{end_year}"
        )

    fig.tight_layout()


# %% Interpolate missing grid cells and save results

interpolated_coeff = np.empty_like(coeff)

for period_index, field in enumerate(coeff):
    if np.isnan(field).any():
        # Use the conditional GRF mean to interpolate grid cells for which
        # the temporal model could not be estimated.
        interpolated_coeff[period_index] = grf(field)
    else:
        interpolated_coeff[period_index] = field.copy()

save_path = result_dir / (
    f"saves_{dataset}_{data_origin}_{start_year}.txt"
)

with save_path.open("w", encoding="utf-8") as file:
    json.dump(interpolated_coeff.tolist(), file)

print(f"Interpolated fields saved to: {save_path}")


# %% Plot posterior fields after GRF interpolation

for period_index, end_year in enumerate(end_years):
    field = interpolated_coeff[period_index]
    field_zoom = zoom(field, (4, 4), order=1)

    fig, ax = plt.subplots(
        figsize=(10, 5),
        subplot_kw={"projection": projection},
    )

    if dataset == "prob_g_0":
        vmax = 1
    else:
        vmax = np.nanmax(interpolated_coeff)

    image = ax.imshow(
        np.flipud(field_zoom),
        cmap="viridis",
        transform=ccrs.PlateCarree(),
        vmax=vmax,
    )

    ax.coastlines(color="black", linewidth=0.5)
    ax.add_feature(
        cfeature.BORDERS,
        edgecolor="black",
        linewidth=0.5,
    )

    gridlines = ax.gridlines(
        draw_labels=True,
        linestyle="--",
        linewidth=0.5,
        color="gray",
    )
    gridlines.top_labels = False
    gridlines.right_labels = False
    gridlines.xformatter = FuncFormatter(
        custom_longitude_formatter
    )
    gridlines.yformatter = FuncFormatter(
        custom_latitude_formatter
    )
    gridlines.ylocator = MaxNLocator(nbins=9)

    fig.colorbar(image, ax=ax, shrink=0.8)

    if dataset == "post_means":
        ax.set_title(
            rf"Magnitude $\gamma(s)$: "
            f"{start_year}-{end_year}",
            fontsize=18,
        )

        # figure_path = result_dir / (
        #     f"lead_coeff_{start_year}_{end_year}.pdf"
        # )
        # fig.savefig(figure_path, bbox_inches="tight")

    else:
        ax.set_title(
            rf"Probability $P(\gamma(s) > 0)$: "
            f"{start_year}-{end_year}",
            fontsize=18,
        )

        # figure_path = result_dir / (
        #     f"prob_g_0_{start_year}_{end_year}.pdf"
        # )
        # fig.savefig(figure_path, bbox_inches="tight")

    fig.tight_layout()


# %% Plot first exceedance of a posterior probability threshold

probability_threshold = 0.9
exceedance_origin = "hadcrut"

exceedance_result_dir = RESULTS_DIR / exceedance_origin
exceedance_path = exceedance_result_dir / (
    f"saves_prob_g_0_{exceedance_origin}_{start_year}.txt"
)

if not exceedance_path.exists():
    raise FileNotFoundError(
        f"Interpolated probability file was not found: "
        f"{exceedance_path}"
    )

with exceedance_path.open("r", encoding="utf-8") as file:
    probability_fields = np.asarray(
        json.load(file),
        dtype=float,
    )

if probability_fields.shape[0] != len(end_years):
    raise ValueError(
        "The number of saved probability fields does not match "
        "the number of configured end years."
    )

year_array = np.asarray(end_years)[:, np.newaxis, np.newaxis]

# Store the end year where the threshold is exceeded and infinity
# where it is not exceeded.
threshold_years = np.where(
    probability_fields > probability_threshold,
    year_array,
    np.inf,
)

first_exceedance = np.min(threshold_years, axis=0)
first_exceedance[~np.isfinite(first_exceedance)] = 0

values = np.unique(first_exceedance)

boundaries = np.concatenate(
    [
        [values[0] - 0.5],
        (values[:-1] + values[1:]) / 2,
        [values[-1] + 0.5],
    ]
)

base_cmap = plt.get_cmap("jet", len(values))
colors = base_cmap(np.arange(len(values)))

# Use white for grid cells where the threshold is never exceeded.
not_exceeded_index = np.where(values == 0)[0]

if not_exceeded_index.size > 0:
    colors[not_exceeded_index[0]] = [1, 1, 1, 1]

exceedance_cmap = mcolors.ListedColormap(colors)
exceedance_norm = mcolors.BoundaryNorm(
    boundaries,
    exceedance_cmap.N,
)

labels = [
    (
        "Not exceeded"
        if value == 0
        else f"{start_year}-{int(value)}"
    )
    for value in values
]

first_exceedance_zoom = zoom(
    first_exceedance,
    (4, 4),
    order=1,
)

fig, ax = plt.subplots(
    figsize=(10, 5),
    subplot_kw={"projection": projection},
)

image = ax.imshow(
    np.flipud(first_exceedance_zoom),
    cmap=exceedance_cmap,
    norm=exceedance_norm,
    transform=ccrs.PlateCarree(),
)

ax.coastlines(color="black", linewidth=0.5)
ax.add_feature(
    cfeature.BORDERS,
    edgecolor="black",
    linewidth=0.5,
)

gridlines = ax.gridlines(
    draw_labels=True,
    linestyle="--",
    linewidth=0.5,
    color="gray",
)
gridlines.top_labels = False
gridlines.right_labels = False
gridlines.xformatter = FuncFormatter(
    custom_longitude_formatter
)
gridlines.yformatter = FuncFormatter(
    custom_latitude_formatter
)
gridlines.ylocator = MaxNLocator(nbins=9)

ax.set_title(exceedance_origin.upper())

handles = [
    mpatches.Patch(
        color=exceedance_cmap(exceedance_norm(value)),
        label=label,
    )
    for value, label in zip(values, labels)
]

fig.legend(
    handles=handles,
    labels=labels,
    loc="lower center",
    bbox_to_anchor=(0.5, -0.1),
    ncol=int(np.ceil(len(labels) / 2)),
    fontsize=12,
)

exceedance_figure_path = exceedance_result_dir / (
    f"exceed_times_{exceedance_origin}_"
    f"{int(probability_threshold * 100)}.png"
)

fig.savefig(
    exceedance_figure_path,
    bbox_inches="tight",
)

print(f"Exceedance map saved to: {exceedance_figure_path}")


# %% Count threshold exceedances over land and ocean

summary_threshold = 0.9
summary_origin = "noaa"
summary_years = [1990, 2000, 2010, 2020, 2026]

summary_lat, summary_lon = load_coordinates(summary_origin)

summary_result_dir = RESULTS_DIR / summary_origin
summary_path = summary_result_dir / (
    f"saves_prob_g_0_{summary_origin}_{start_year}.txt"
)

if not summary_path.exists():
    raise FileNotFoundError(
        f"Interpolated probability file was not found: "
        f"{summary_path}"
    )

with summary_path.open("r", encoding="utf-8") as file:
    summary_fields = np.asarray(
        json.load(file),
        dtype=float,
    )

lon_grid, lat_grid = np.meshgrid(
    summary_lon,
    summary_lat,
)

land_mask = globe.is_land(lat_grid, lon_grid)

for end_year in summary_years:
    period_index = end_years.index(end_year)
    field = summary_fields[period_index]

    valid_mask = np.isfinite(field)
    land_valid = land_mask & valid_mask
    ocean_valid = ~land_mask & valid_mask

    all_exceeding = (field > summary_threshold) & valid_mask
    land_exceeding = (field > summary_threshold) & land_valid
    ocean_exceeding = (field > summary_threshold) & ocean_valid

    print(f"Timespan: {start_year}-{end_year}")

    print(
        f"All grid cells exceeding {summary_threshold}: "
        f"{np.sum(all_exceeding)}/{np.sum(valid_mask)}"
    )

    print(
        f"Ocean grid cells exceeding {summary_threshold}: "
        f"{np.sum(ocean_exceeding)}/{np.sum(ocean_valid)}"
    )

    print(
        f"Land grid cells exceeding {summary_threshold}: "
        f"{np.sum(land_exceeding)}/{np.sum(land_valid)}"
    )

    print()